// Generated by CoffeeScript 1.8.0
(function() {
  var Configurator, Pbx, Trunk;

  Configurator = require('nafnaf').Configurator;

  Trunk = require('./trunk');

  Pbx = (function() {
    function Pbx(dirname) {
      this.trunks = [];
      this.configurator = new Configurator(dirname);
    }

    Pbx.prototype.init = function(callback) {
      return this.configurator.loadFiles(callback);
    };

    Pbx.prototype.addTrunk = function(obj) {
      var trunk;
      trunk = new Trunk(this.configurator, obj);
      trunk.save(function() {
        return console.log('saved');
      });
      return this.trunks.push(trunk);
    };

    Pbx.prototype.getTrunks = function() {
      return this.trunks;
    };

    Pbx.prototype.loadTrunks = function(callback) {
      var key, object, result;
      result = {};
      object = this.configurator.files['users.conf'];
      for (key in object) {
        if (object.hasOwnProperty(key) && key.substr(0, 6) === 'trunk_') {
          result[key] = object[key];
        }
      }
      return callback(result);
    };

    return Pbx;

  })();

  module.exports = Pbx;

}).call(this);
